import * as colors from './colors';

const size = {
  container: 1056,
  footnote: 10,
  small: 12,
  regular: 14,
  H5: 16,
  H4: 18,
  H3: 24,
  H2: 32,
  H1: 36,
  H0: 48,
  spacing_1: 24,
  spacing_2: 16,
  spacing_3: 12,
  spacing_4: 8,
  spacing_5: 4,
  separator: 1,
  border: 1,
  borderRadius: 5,
  red: colors.ACCENT_RED,
  blue: colors.ACCENT_BLUE,
  yellow: colors.ACCENT_YELLOW,
  green: colors.ACCENT_GREEN,
  orange: colors.ACCENT_ORANGE,
  halfWhite: colors.HALF_WHITE,
};

const collections = {
  1: {
    id: 1,
    name: 'Dark Theme',
    text: colors.INVERSE_TEXT,
    a1: colors.ACCENT_RED,
    a2: colors.ACCENT_BLUE,
    a3: colors.ACCENT_YELLOW,
    a4: colors.ACCENT_BLUE,
    a5: colors.ACCENT_ORANGE,
    bg: colors.ONYX_SLATE,
    bg2: colors.ONYX_BLACK,
    bg3: colors.ONYX_EXTRA_SLATE,
    bg3_75: colors.ONYX_EXTRA_SLATE_75,
    bg2_50: colors.ONYX_BLACK_50,
    bg2_75: colors.ONYX_BLACK_75,
    borderColor: colors.INVERSE_TEXT(0.05),
    shadow: colors.INVERSE_TEXT(0.1),
    ...size,
  },
  0: {
    id: 0,
    name: 'Light Theme',
    text: colors.TEXT,
    a1: colors.ACCENT_RED,
    a2: colors.ACCENT_BLUE,
    a3: colors.ACCENT_YELLOW,
    a4: colors.ACCENT_GREEN,
    a5: colors.ACCENT_ORANGE,
    bg: colors.BG,
    bg2: colors.BG,
    bg3: colors.CONTENT_BG,
    borderColor: colors.TEXT(0.1),
    shadow: colors.TEXT(0.1),
    ...size,
  },
};

export default collections;
