export const UPDATE_THEME = 'app/UPDATE_THEME';
export const UPDATE_USERS = 'app/UPDATE_USERS';
export const UPDATE_ACTIVE_EVENTS = 'app/UPDATE_ACTIVE_EVENTS';
export const UPDATE_IDLE_EVENTS = 'app/UPDATE_IDLE_EVENTS';
export const UPDATE_PENDING_EVENTS = 'app/UPDATE_PENDING_EVENTS';
export const UPDATE_FEED_EVENTS = 'app/UPDATE_FEED_EVENTS';
export const UPDATE_INVITATIONS = 'app/UPDATE_INVITATIONS';
export const SAVE_USER = 'app/SAVE_USER';
